### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by sancelot** [pinglu85/IKSolver-for-threejs#37]
Some issue , you are referencing this.target and this.ikchain, but it seems being this._ikchain and this._target 
https://github.com/pinglu85/IKSolver-for-threejs/blob/8d4e61253fd5d32e02a98417cc21fcd17b8c5d31/src/ik/IKSolver.js#L37

**Comment by pinglu85** [comment]
There are getters for `this._ikChain` and `this._target`. When `this.ikChain` and `this.target` are read, the getters are executed.

Example: 

```js
class Person {
  constructor() {
    this._name = 'foo';
  }

  get name() {
    return this._name;
  }

  say() {
    if (this.name === 'foo') {
      console.log('name is foo');
      return;
    }

    console.log('hello');
  }
}

const p = new Person();

p.say();
// logs 'name is foo'
```
https://jsitor.com/vogEPZhYA
